### ISSUE TITLE
Unauthenticated users being redirected to login

### ISSUE THREAD

**Issue by StevePrice** [cakemanager/docs#2]
It seems like 
    public function isAuthorized($user) {

```
    $this->Authorizer->action(['*'], function($auth, $user) {
        $auth->allowRole([4]);
    });

    return $this->Authorizer->authorize();
}
```

in appcontroler.php is not working correctly. 

Use case:
Home page is accessed by unauthenticated visitor. Link (menu item) to a registration page.
Expected result:
The controller should let users with unauthenticated roles see the some page.
Actual result:
Visitor are redirected to login page.

**Comment by bobmulder** [comment]
Hey Steve,

Thank you for using and testing the CakeManager. I understand you are using role '4' (`unregistered`).
This role is reserved for ACL (When using ACL, you are able to set unregistered users as role 4, so you can define them in your admin-panel). 
So, currently role 4 is not used. 

You want to allow unlogged users to a page. For that the original `AuthComponent` from CakePHP itself is very useful. Take a look at this: http://book.cakephp.org/3.0/en/controllers/components/authentication.html#making-actions-public.

Refering to the url you can use the following to allow a user to the index page:

```
// in your initialize method from your AppController
$this->Auth->allow(['display]);
```

When using this, unlogged users are allowed to the `display`action. The `AuthorizerComponent` from the CakeManager is used to protect pages when an user is logged in to protect per role.

I hope this made it clear. Do you have any ideas to make this clear? Is this working well or do you have suggestions? 

Good luck ;)

**Comment by StevePrice** [comment]
Bob,
Thanks for your prompt reply, and yes, your directions are clear.  I did changed it to
$this->Auth->allow(['display']);
and it worked! 
I did not realize that unregistered users (4) are not used. My mistake, I guess I still have more to learn.
I may have more questions in the future, but for now, I think Cakemanager is a great addition to the cake 3 ecosystem.  
Best regards
Steve

**Comment by bobmulder** [comment]
I will document this stuff better. I think it's not clear enough...
